# Value types
const TRE_TYPE_INTEGER = 1
const TRE_TYPE_FLOAT = 2
const TRE_TYPE_STRING = 3
const TRE_TYPE_DATE = 4
const TRE_TYPE_DATETIME = 5
const TRE_TYPE_TIME = 6
const TRE_TYPE_CATEGORY = 7

# Transformation types
const TRE_TRANSFORMATION_TYPE_INGEST = 1
const TRE_TRANSFORMATION_TYPE_TRANSFORM = 2

# Transformation statuses
const TRE_TRANSFORMATION_STATUS_UNVERIFIED = 1
const TRE_TRANSFORMATION_STATUS_VERIFIED = 2

# asset type
const TRE_DATASET = 1
const TRE_DOCUMENT = 2

# Study types
const TRE_STUDY_TYPE_HDSS = 1
const TRE_STUDY_TYPE_COHORT = 2
const TRE_STUDY_TYPE_SURVEY = 3
const TRE_STUDY_TYPE_PANEL = 4
const TRE_STUDY_TYPE_CASE_CONTROL = 5
const TRE_STUDY_TYPE_RCT = 6

# REDCap metadata types
const _VT_INT     = TRE_TYPE_INTEGER
const _VT_FLOAT   = TRE_TYPE_FLOAT
const _VT_STRING  = TRE_TYPE_STRING
const _VT_DATE    = TRE_TYPE_DATE
const _VT_DATETIME= TRE_TYPE_DATETIME
const _VT_TIME    = TRE_TYPE_TIME
const _VT_ENUM    = TRE_TYPE_CATEGORY
