# Value types
const TRE_TYPE_INTEGER = 1
const TRE_TYPE_FLOAT = 2
const TRE_TYPE_STRING = 3
const TRE_TYPE_DATE = 4
const TRE_TYPE_DATETIME = 5
const TRE_TYPE_TIME = 6
const TRE_TYPE_CATEGORY = 7

# Transformation types
const TRE_TRANSFORMATION_TYPE_INGEST = 1
const TRE_TRANSFORMATION_TYPE_TRANSFORM = 2

# Transformation statuses
const TRE_TRANSFORMATION_STATUS_UNVERIFIED = 1
const TRE_TRANSFORMATION_STATUS_VERIFIED = 2

# Unit of analysis
const TRE_UNIT_OF_ANALYSIS_INDIVIDUAL = 1
const TRE_UNIT_OF_ANALYSIS_AGGREGATION = 2

# Study types
const TRE_STUDY_TYPE_DSS = 1
const TRE_STUDY_TYPE_COHORT = 2
const TRE_STUDY_TYPE_SURVEY = 3
const TRE_STUDY_TYPE_PANEL = 4
const TRE_STUDY_TYPE_CASE_CONTROL = 5
const TRE_STUDY_TYPE_RCT = 6